### ISSUE TITLE
Crashes when trying to hit the delete button on a player more than once in a row

### ISSUE THREAD

**Issue by RyanSimon** [ryan-simon/simple-scoreboard#1]
Proposed fix is to disable the delete button's onClick after it has been pressed once. Stack trace below:

02-02 10:43:50.397    3748-3748/me.ryansimon.simplescoreboard E/AndroidRuntime﹕ FATAL EXCEPTION: main
    Process: me.ryansimon.simplescoreboard, PID: 3748
    java.lang.ArrayIndexOutOfBoundsException: length=12; index=-1
            at java.util.ArrayList.remove(ArrayList.java:405)
            at me.ryansimon.simplescoreboard.PlayerItemAdapter$3.onClick(PlayerItemAdapter.java:114)
            at android.view.View.performClick(View.java:4456)
            at android.view.View$PerformClick.run(View.java:18462)
            at android.os.Handler.handleCallback(Handler.java:733)
            at android.os.Handler.dispatchMessage(Handler.java:95)
            at android.os.Looper.loop(Looper.java:136)
            at android.app.ActivityThread.main(ActivityThread.java:5086)
            at java.lang.reflect.Method.invokeNative(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:515)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:785)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:601)
            at dalvik.system.NativeStart.main(Native Method)

**Comment by RyanSimon** [comment]
Fixed in commit dc13907
