### ISSUE TITLE
Crashes if entering a score that exceeds the limit of an int

### ISSUE THREAD

**Issue by RyanSimon** [ryan-simon/simple-scoreboard#2]
Proposed solution is to limit max number (or number of digits) that can be input. Stack trace below:

02-02 10:51:21.489    3917-3917/me.ryansimon.simplescoreboard E/AndroidRuntime﹕ FATAL EXCEPTION: main
    Process: me.ryansimon.simplescoreboard, PID: 3917
    java.lang.NumberFormatException: Invalid int: "644656353464646235926535656565656565662656565"
            at java.lang.Integer.invalidInt(Integer.java:137)
            at java.lang.Integer.parse(Integer.java:377)
            at java.lang.Integer.parseInt(Integer.java:365)
            at java.lang.Integer.parseInt(Integer.java:331)
            at java.lang.Integer.valueOf(Integer.java:489)
            at me.ryansimon.simplescoreboard.ScoreManagerActivity.onPositive(ScoreManagerActivity.java:152)
            at me.ryansimon.simplescoreboard.NewPlayerDialogFragment$2.onClick(NewPlayerDialogFragment.java:77)
            at com.android.internal.app.AlertController$ButtonHandler.handleMessage(AlertController.java:166)
            at android.os.Handler.dispatchMessage(Handler.java:102)
            at android.os.Looper.loop(Looper.java:136)
            at android.app.ActivityThread.main(ActivityThread.java:5086)
            at java.lang.reflect.Method.invokeNative(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:515)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:785)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:601)
            at dalvik.system.NativeStart.main(Native Method)

**Comment by RyanSimon** [comment]
Fixed by limiting user input to be less than MAX_INT
